<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="https://raw.githubusercontent.com/user11117s/grassmessage-schemas/refs/heads/main/components.xsd"/>

    <!-- ChatGPT carried. I don't know much about XSD. -->

    <xs:simpleType name="normalizedFloat">
        <xs:restriction base="xs:float">
            <xs:minExclusive value="0"/>
            <xs:maxExclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <!--
    _______________
    Top-level setup
    _______________
    -->

    <!-- Types -->

    <xs:complexType name="messageType">
        <xs:complexContent>
            <xs:extension base="compositeComponent">
                <xs:attribute name="name" type="xs:Name" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="messagesType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="message" type="messageType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="middleColorStopType">
        <xs:simpleContent>
            <xs:extension base="hexColor">
                <xs:attribute name="position" type="normalizedFloat" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="gradientType">
        <xs:sequence>
            <xs:element name="start" type="hexColor"/>
            <xs:element name="middle" minOccurs="0" maxOccurs="unbounded" type="middleColorStopType"/>
            <xs:element name="end" type="hexColor"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:Name" use="required"/>
    </xs:complexType>

    <xs:simpleType name="namedColor">
        <xs:restriction base="xs:string">
            <xs:enumeration value="black"/>
            <xs:enumeration value="dark_blue"/>
            <xs:enumeration value="dark_green"/>
            <xs:enumeration value="dark_aqua"/>
            <xs:enumeration value="dark_red"/>
            <xs:enumeration value="dark_purple"/>
            <xs:enumeration value="gold"/>
            <xs:enumeration value="gray"/>
            <xs:enumeration value="dark_gray"/>
            <xs:enumeration value="blue"/>
            <xs:enumeration value="green"/>
            <xs:enumeration value="aqua"/>
            <xs:enumeration value="red"/>
            <xs:enumeration value="light_purple"/>
            <xs:enumeration value="yellow"/>
            <xs:enumeration value="white"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="styleType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="color">
            <xs:simpleType>
                <xs:union memberTypes="namedColor hexColor"/>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="shadowColor" type="hexColor8"/>
        <xs:attribute name="font" type="xs:string"/>
        <xs:attribute name="bold" type="xs:boolean" default="false"/>
        <xs:attribute name="italic" type="xs:boolean" default="false"/>
        <xs:attribute name="underlined" type="xs:boolean" default="false"/>
        <xs:attribute name="strikethrough" type="xs:boolean" default="false"/>
        <xs:attribute name="obfuscated" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="gradientsType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="gradient" type="gradientType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stylesType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="style" type="styleType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Root -->

    <xs:element name="grass">
        <xs:complexType>
            <xs:all>
                <xs:element name="messages" type="messagesType"/>
                <xs:element name="gradients" type="gradientsType" minOccurs="0"/>
                <xs:element name="styles" type="stylesType" minOccurs="0"/>
            </xs:all>
        </xs:complexType>

        <xs:key name="msgNames">
            <xs:selector xpath="messages/message"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:key name="gradientNames">
            <xs:selector xpath="gradients/gradient"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:key name="styleNames">
            <xs:selector xpath="styles/style"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref name="msgInstances" refer="msgNames">
            <xs:selector xpath=".//embed_msg"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
        <xs:keyref name="gradInstances" refer="gradientNames">
            <xs:selector xpath=".//gradref"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
        <xs:keyref name="styleInstances" refer="styleNames">
            <xs:selector xpath=".//styleref"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
    </xs:element>
</xs:schema>
